language: python
sudo: required
dist: xenial
python: "3.7"
install:
  - pip install pipenv
  - pipenv install --dev
  # Decrypt the service account used for end-to-end testing
  - openssl aes-256-cbc -K $encrypted_51f431aaca2e_key -iv $encrypted_51f431aaca2e_iv -in travis-ci-test-suite-service-account.json.enc -out travis-ci-test-suite-service-account.json -d
script:
  - invoke test
